server:
  port: 8080
spring:
  application:
    name: your-app-name
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always