apiVersion: apps/v1
kind: Deployment
metadata:
  name: bhavsar-service-deployment
spec:
  replicas: 2
  progressDeadlineSeconds: 1200
  selector:
    matchLabels:
      app: bhavsar-service
  template:
    metadata:
      labels:
        app: bhavsar-service
    spec:
      containers:
        - name: bhavsar-service
          image: 122814843741.dkr.ecr.eu-north-1.amazonaws.com/bhavsar-repository:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5