apiVersion: apps/v1
kind: Deployment
metadata:
  name: bhavsar-service-deployment
spec:
  replicas: 1  # Start with 1 replica
  selector:
    matchLabels:
      app: bhavsar-service
  template:
    metadata:
      labels:
        app: bhavsar-service
    spec:
      containers:
        - name: bhavsar-service
          image: 122814843741.dkr.ecr.eu-north-1.amazonaws.com/bhavsar-repository:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          # Remove health checks temporarily